Run shfmt with -i 0 (tab indentation)

diff --git a/common/bin/download-verify-yarn b/common/bin/download-verify-yarn
--- a/common/bin/download-verify-yarn
+++ b/common/bin/download-verify-yarn
@@ -9,8 +9,8 @@ set -e
 
 package_version=$1
 if [ -z "$package_version" ]; then
-    echo "Yarn package version not provided. Should be something like '1.22.19'"
-    exit 1
+	echo "Yarn package version not provided. Should be something like '1.22.19'"
+	exit 1
 fi
 
 # Yarn 2+ (aka: "berry") is hosted under a different npm package.
@@ -30,8 +30,8 @@ shasum=$(shasum -b -a 512 yarn-v"${package_version}".tar.gz | awk '{ print $1 }'
 actual_integrity="sha512-${shasum}"
 published_integrity=$(curl -sSf "https://registry.npmjs.com/${package_name}/${package_version}" | jq -r '.dist.integrity')
 if [ "$actual_integrity" != "$published_integrity" ]; then
-    echo "Couldn't verify package integrity. Expected '$published_integrity', got '$actual_integrity'." >&2
-    exit 1
+	echo "Couldn't verify package integrity. Expected '$published_integrity', got '$actual_integrity'." >&2
+	exit 1
 fi
 
 # Build the npm signing key from published npm key data. This section assumes there
