Update shellcheck and run shfmt

diff --git a/common/bin/download-verify-yarn b/common/bin/download-verify-yarn
--- a/common/bin/download-verify-yarn
+++ b/common/bin/download-verify-yarn
@@ -9,14 +9,13 @@ set -e
 
 package_version=$1
 if [ -z "$package_version" ]; then
-  echo "Yarn package version not provided. Should be something like '1.22.19'"
-  exit 1
+    echo "Yarn package version not provided. Should be something like '1.22.19'"
+    exit 1
 fi
 
 # Yarn 2+ (aka: "berry") is hosted under a different npm package.
 major_version=$(echo "$package_version" | cut -d "." -f 1)
 package_name=$([ "$major_version" -ge 2 ] && echo "@yarnpkg/cli-dist" || echo "yarn")
-
 
 echo "Downloading yarn tarball..." >&2
 url=$(curl -sSf "https://registry.npmjs.com/${package_name}/${package_version}" | jq -r '.dist.tarball')
@@ -31,8 +30,8 @@ shasum=$(shasum -b -a 512 yarn-v"${package_version}".tar.gz | awk '{ print $1 }'
 actual_integrity="sha512-${shasum}"
 published_integrity=$(curl -sSf "https://registry.npmjs.com/${package_name}/${package_version}" | jq -r '.dist.integrity')
 if [ "$actual_integrity" != "$published_integrity" ]; then
-  echo "Couldn't verify package integrity. Expected '$published_integrity', got '$actual_integrity'." >&2
-  exit 1
+    echo "Couldn't verify package integrity. Expected '$published_integrity', got '$actual_integrity'." >&2
+    exit 1
 fi
 
 # Build the npm signing key from published npm key data. This section assumes there
